apps/user/urls.py
from django.urls import  path
from rest_framework import routers

from .views.user_views import ( MeApiView, UserCreateApiView, UserListApiView, UserDetailApiView,
                PasswordResetView, PasswordResetDoneView, UserUpdateApiView, ListCollaboratorsApi )

from .views.user_views import (UserListView, UserAddView, UserDetailView, UserUpdateView, UserListExportView)
from .views.user_views import (UserDeleteView, UserDeactivateView, UserDestroy)

from .views.roles_views import RoleListView, RoleAddView, RoleDetailView, RoleUpdateView, RoleDeleteView

from .views.subrole_views import (SubroleListView, SubroleCreateView, SubroleDetailView, SubroleUpdateView)

from .views.roles_views import RoleApiListView

from .views.subrole_views import SubRoleApiListView, SubRolePermissionsApiListView


router = routers.SimpleRouter()

# router.register('', UserViewSet, basename='urls_user')


urlpatterns = [
    # ========================  Api User Endpoints  ===============================
    path('me/', MeApiView.as_view()),
    path('list/', UserListApiView.as_view()),
    path('create/', UserCreateApiView.as_view()),
    path('view/<int:pk>/', UserDetailApiView.as_view()),
    path('update/<int:pk>/', UserUpdateApiView.as_view()),
    path('password/reset/', PasswordResetView.as_view()),
    path('password/reset/done/<slug:slug>/', PasswordResetDoneView.as_view()),
    path('delete/', UserDeleteView.as_view(), name=UserDeleteView.url_name),
    path('deactivate/', UserDeactivateView.as_view(), name=UserDeactivateView.url_name),
    path('destroy-api/<int:pk>/', UserDestroy.as_view()),
    path('collaborators/', ListCollaboratorsApi.as_view()),


    # ============================= Templates Views User =================================
    path('viewlist/', UserListView.as_view(), name=UserListView.url_name),
    path('list/export/', UserListExportView.as_view(), name=UserListExportView.url_name),
    path('viewcreate/', UserAddView.as_view(), name=UserAddView.url_name),
    path('view/<int:pk>/detail/', UserDetailView.as_view(), name=UserDetailView.url_name),
    path('view/<int:pk>/update/', UserUpdateView.as_view(), name=UserUpdateView.url_name),

    # ============================= Templates Views Role =================================
    path('role/list/', RoleListView.as_view(), name=RoleListView.url_name),
    path('role/create/', RoleAddView.as_view(), name=RoleAddView.url_name),
    path('role/<int:pk>/detail/', RoleDetailView.as_view(), name=RoleDetailView.url_name),
    path('role/<int:pk>/update/', RoleUpdateView.as_view(), name=RoleUpdateView.url_name),
    path('role/delete/', RoleDeleteView.as_view(), name=RoleDeleteView.url_name),


    # ============================= Templates Views SubRole extends from GROUP ===========
    path('subrole/list/', SubroleListView.as_view(), name=SubroleListView.url_name),
    path('subrole/create/', SubroleCreateView.as_view(), name=SubroleCreateView.url_name),
    path('subrole/<int:pk>/detail/', SubroleDetailView.as_view(), name=SubroleDetailView.url_name),
    path('subrole/<int:pk>/update/', SubroleUpdateView.as_view(), name=SubroleUpdateView.url_name),
    
    # ============================= API Views SubRole  ==================================
    path('role/api/list/', RoleApiListView.as_view(), name="role-apilist"),
    path('subrole/api/list/<int:role_id>/', SubRoleApiListView.as_view(), name="subrole-apilist"), #BACKOFFICE
    path('subrole/permissions/api/list/<int:pk>/', SubRolePermissionsApiListView.as_view(), name="subrole-permissions-apilist"), #BACKOFFICE


]

urlpatterns += router.urls

config/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import  include, path

from apps.dashboard import urls as dashboard_urls
from apps.company import urls as company_urls
from apps.coordinates import urls as coordinates_urls
from apps.formulario import urls as formulario_urls
from apps.proforestform import urls as proforestform_urls
from apps.questionsbank import urls as questionbank_urls
from apps.traceability import urls as traceability_urls
from apps.supplybase import urls as supplybase_urls
from apps.user import urls as user_urls
from apps.onedrive import urls as onedrive_urls
from apps.emailcustom import urls as emailcustom_urls


from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)


urlpatterns = [
    #admin de Django
    path('adminproforest/', admin.site.urls), 


    #Include Auth urls
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    
    #Include dashboard app
    path('', include(dashboard_urls)),

    #Include Urls of Company APP
    path('company/', include(company_urls)),

    #Include Urls of Question Bank
    path('questionbank/', include (questionbank_urls)),

    #Include Urls of ProforestForm
    path('proforestform/', include (proforestform_urls)),

    #Include Urls of Formularios
    path('formulario/', include (formulario_urls)),
    #Include Traceability URLS

    path('traceability/', include (traceability_urls)),

    #Include User custom Urls
    path('users/', include(user_urls)),

    #Include Cities app Urls
    path('cities/', include('apps.cities.urls')),

    #Coordinates Validate Views
    path('coordinates/', include(coordinates_urls)),

    #Dependency Supply Base
    path('supplybase/', include(supplybase_urls)),

    #Email Template Views
    path('email/', include(emailcustom_urls)),

    #Landing for onedrive Oauth2
    path('onedrive/', include(onedrive_urls)),


    #Generic auth Views
    path('auth/login/',  auth_views.LoginView.as_view( template_name='adminlte/base/login.html' ), name='login'),
    path('auth/logout/', auth_views.logout_then_login, name='logout'),

    #HelperView to change Language
    path('i18n/', include('django.conf.urls.i18n'))

]

apps/user/models.py
from apps.user.views.groups import Check_user_in_groups

from cities_light.models import Country, Region, SubRegion
from config import settings

from apps.utils.models import base_model
from django.contrib.auth.models import (AbstractUser, BaseUserManager, Group)
from django.db import models
from django.dispatch import receiver
from django.core.mail import EmailMessage
from django.db.models.signals import pre_save, post_save
from django.template.loader import render_to_string
from django.utils.translation import gettext_lazy as _


import uuid
import random


class Role(base_model.BaseModel):
    name = models.CharField(max_length=126)
    groups = models.ManyToManyField(
        Group,
        blank = True,
    )
    class Meta:
        ordering = ['name']

    def __str__(self):
        return str(self.name)

class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('Users require an email field')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):

        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)

class User(AbstractUser,):
    username = None
    last_name = None
    email = models.EmailField('email address', unique=True)
    USERNAME_FIELD = 'email'
    """Use the email as unique username."""
    REQUIRED_FIELDS = ['first_name', 'surname']
    first_name = models.CharField(max_length=128)
    second_name = models.CharField(max_length=128, blank=True)
    surname = models.CharField(max_length=128)
    second_surname = models.CharField(max_length=128, blank=True)
    image_profile = models.ImageField(
        upload_to = 'user-profile/img/',
        null = True,
        blank = True,
    )
    created_date = models.DateTimeField(auto_now_add=True)
    role = models.ForeignKey(
        Role,
        on_delete = models.PROTECT,
        null = True,
        blank = True,
    )
    #Contact Info
    company = models.ForeignKey(
        'company.Company',
        on_delete = models.PROTECT,
        blank=True,
        null=True,
    )
    indicative = models.CharField(max_length=16)
    phone = models.CharField(max_length=16)
    country = models.ForeignKey(
        Country,
        on_delete=models.PROTECT,
        blank=True,
        null=True
        )
    region = models.ForeignKey(
        Region,
        on_delete=models.PROTECT,
        blank=True,
        null=True
    )
    city = models.ForeignKey(
        SubRegion,
        on_delete=models.PROTECT,
        blank=True,
        null=True
    )
    accept_terms_conditions = models.BooleanField(default=False)
    accept_terms_date = models.DateTimeField(blank=True, null=True)
    status = models.BooleanField(default=True)

    objects = UserManager()

    class Meta:
        ordering = ['pk']
        permissions=[
            ("change_own_user", "Can change own user")]
        

    def password_reset_mail(self, password_reset_slug:str ) -> None:
        url_password_reset_done = f'{settings.URL_PASSWORD_RESET}{password_reset_slug}'

        email_info = {
            'subject': 'Proforest - Restaurar contraseña.',
            'template': 'password_reset',
            'to': [self.email],
            'context': {
                'user': f'{self.first_name} {self.second_name}' if self.first_name else self.email,
                'url_password_reset_done': url_password_reset_done,
                
            },
        }

        self.send_mail(**email_info)

    def verify_email(self):
        email_info = {
            'subject': 'Proforest - Confirmación de cuenta.',
            'template': 'initial_verify_email',
            'to': [self.email],
            'context': {
                'user': f'{self.first_name} {self.second_name}' if self.first_name else self.email,
                'token': self.slug
            },
        }

        self.send_mail(**email_info)

    def send_mail(self, subject: str, to: list, template: str, context: dict) -> None:
        body = render_to_string(
            f'mail/{template}.html',
            context
        )
        email_message = EmailMessage(
            **{
                'subject': subject,
                'from_email': settings.EMAIL_FROM_DIR,
                'to': to,
                'body': body
            }
        )

        email_message.content_subtype = 'html'
        email_message.send()
    
    def get_full_name(self) -> str:
        return ' '.join((self.first_name, self.second_name, self.surname, self.second_surname))

    def get_image_profile_url(self):
        if self.image_profile:
            return self.image_profile.url
        else:
            return ''
    
    def get_country_display(self):
        if self.country:
            
            return self.country.name
        return _('No Register')

    def get_region_display(self):
        if self.region:
            return self.region.name
        return _('No Register')

    def get_city_display(self):
        if self.city:
            return self.city.name
        return _('No Register')

   

@receiver(post_save, sender=User)
def update_company_asociated(sender, **kwargs):
    from apps.company.models.company import Company #avoid circular importation
    instance = kwargs.get('instance')
    if instance.company:
        update_company = instance.company
        update_company.has_responsable = True
        update_company.save()
    try:
        groups = ['SUPERUSUARIO']
        if Check_user_in_groups(instance, groups):
            
            update_company = instance.company
            update_company.has_superuser = True
            update_company.save()
    except:
        pass #No company
    if instance.status == True:
        instance.is_active = True
    else :
        instance.is_active = False
    return

@receiver(pre_save, sender=User)
def update_company_asociated(sender, **kwargs):
    instance = kwargs.get('instance')
   
    if instance.status == True:
        instance.is_active = True
    else :
        instance.is_active = False
    return

class PasswordReset(base_model.BaseModel):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True, blank=True)
    recovery_code = models.IntegerField(blank=True,null=True)

    def get_recovery_code_str(self):
        str_recovery_code = ''
        for l in str(self.recovery_code):
            str_recovery_code += f'{l}'

        return str_recovery_code.strip()

@receiver(pre_save, sender=PasswordReset)
def slug_handler(sender, **kwargs):
    instance = kwargs.get('instance')

    if not instance.slug:
        for _ in range(16):
            slug = uuid.uuid4()

            if not sender.objects.filter(slug=slug).exists():
                instance.slug = slug
                return

apps/formulario/views/usercreate_views.py
from apps.user.models import User, Role
from django.contrib.auth.models import (Group)
from datetime import datetime
from apps.company.models.company import CompanyUserFormKey

from rest_framework.views import APIView
from rest_framework.response import Response

from apps.user.serializers.user_serializers import CreateUserFormSerializer

class CreateUserKey(APIView):
    permission_classes = []
    serializer_class = CreateUserFormSerializer

    def post(self, request, *args, **kwargs):

        ''' Valida que el email enviado por el usuario sea valido '''
        dataform = dict(request.data)
        slug_key = request.data['key']
        if User.objects.filter(email=dataform['email']).exists():
            key = CompanyUserFormKey.objects.get(slug = slug_key)
            key.delete()
            return Response(
                {
                    "type": "validation_error",
                    "errors": [
                        {
                            "code": "assigned_user",
                            "detail": "The user already exists in the database ",
                            "attr": "User"
                        }
                    ]
                },
                403
            )  

        if CompanyUserFormKey.objects.filter(slug = slug_key).exists():
            key = CompanyUserFormKey.objects.get(slug = slug_key)
            dataform['company'] = key.company.id
            serializer = CreateUserFormSerializer(data=dataform)

            if serializer.is_valid():
                new_user = serializer.save(
                    role = Role.objects.get(name='CLIENTE'),
                    accept_terms_conditions = True,
                    accept_terms_date = datetime.now()  
                )
                group_usuario = Group.objects.get(name='USUARIO')
                group_usuario.user_set.add(new_user)
                key.delete()

                return Response(
                            {
                                "type": "validation_error",
                                "errors": [
                                    {   "code": "error_in_form",
                                        "detail": "This form is incomplete ",
                                        "attr": "new user"
                                    }
                                ] }, 201
                        )
            else:
                return Response( { "type": "bad_request", "errors": serializer.errors }, 400 )
        else:
            return Response(
                        {
                            "type": "validation_error",
                            "errors": [
                                {   "code": "not_exists",
                                    "detail": "This link is Useless ",
                                    "attr": "email"
                                }
                            ] }, 401
                    )
            

        

apps/user/views/groups.py
from django.db.models import Q

def Check_user_in_groups(user, groups):
    return user.groups.filter(Q(name__in=groups)).exists()

apps/user/templates/user/user/user_update.html
{% extends 'adminlte/base/base.html' %}
{% load static i18n %}
{% load widget_tweaks %}

{% block extra_css %}
{% endblock %}

{% block content %}
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">{% trans "Update" %}</h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="{% url 'proforest-dashboard1' %}">{% trans "Home" %}</a></li>
          <li class="breadcrumb-item"><a href="{% url 'user-list' %}">{% trans "Users" %}</a></li>
          <li class="breadcrumb-item"><a href="{% url 'user-detail' object.pk %}">{{ object.email }}</a></li>
          <li class="breadcrumb-item active">{% trans "Update" %}</li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <!-- /.col -->
      <div class="col-md-12">
        <div class="card">
          <div class="card-header p-2">
            <ul class="nav nav-pills">
              <li class="nav-item"><a class="nav-link active" href="#general" data-toggle="tab">{% trans "General information" %}</a></li>
            </ul>
          </div><!-- /.card-header -->
          <div class="card-body">
            <div class="tab-content">
              <div class="active tab-pane" id="general">
                <form class="form-horizontal" action="" method="post">{% csrf_token %}

                  <div class="row">

                    <div class="col-md-6">
                      <div class="form-group row">
                        <label for="" class="col-md-3 col-form-label">{% trans "Email" %}</label>
                        <div class="col-md-9">
                          {% render_field form.email class="form-control" %}
                          {% for error in form.email.errors %}
                            <p class="text-danger">{{ error }}</p>
                          {% endfor %}
                        </div>
                      </div>
                    </div>

                    <div class="col-md-6">
                      <div class="form-group row">
                        <label for="" class="col-md-3 col-form-label">{% trans "Active User" %}</label>

                        <label for="" class="col-md-9 col-form-label">
                          {% render_field form.status  data-bootstrap-switch=""%}
                        </label>
                        
                      </div>
                    </div>

                  </div>

                  <div class="row">

                    <div class="col-md-6">
                      <div class="form-group row">
                        <label for="" class="col-md-3 col-form-label">{% trans "First Name" %}</label>
                        <div class="col-md-9">
                          {% render_field form.first_name class="form-control" %}
                          {% for error in form.first_name.errors %}
                            <p class="text-danger">{{ error }}</p>
                          {% endfor %}
                        </div>
                      </div>
                    </div>

                    <div class="col-md-6">
                      <div class="form-group row">
                        <label for="" class="col-md-3 col-form-label">{% trans "Second Name" %}</label>
                        <div class="col-md-9">
                          {% render_field form.second_name class="form-control" %}
                          {% for error in form.second_name.errors %}
                            <p class="text-danger">{{ error }}</p>
                          {% endfor %}
                        </div>
                      </div>
                    </div>

                    <div class="col-md-6">
                      <div class="form-group row">
                        <label for="" class="col-md-3 col-form-label">{% trans "Surname" %}</label>
                        <div class="col-md-9">
                          {% render_field form.surname class="form-control" %}
                          {% for error in form.surname.errors %}
                            <p class="text-danger">{{ error }}</p>
                          {% endfor %}
                        </div>
                      </div>
                    </div>

                    <div class="col-md-6">
                      <div class="form-group row">
                        <label for="" class="col-md-3 col-form-label">{% trans "Second Surname" %}</label>
                        <div class="col-md-9">
                          {% render_field form.second_surname class="form-control" %}
                          {% for error in form.second_surname.errors %}
                            <p class="text-danger">{{ error }}</p>
                          {% endfor %}
                        </div>
                      </div>
                    </div>

                    <div class="col-md-6">
                      <div class="form-group row">
                        <label for="" class="col-md-3 col-form-label">{% trans "Phone" %}</label>
                        <div class="col-md-9">
                          {% render_field form.phone class="form-control" %}
                          {% for error in form.phone.errors %}
                            <p class="text-danger">{{ error }}</p>
                          {% endfor %}
                        </div>
                      </div>
                    </div>

                    <div class="col-md-6">
                      <div class="form-group row">
                        <label for="" class="col-md-3 col-form-label">{% trans "Country" %}</label>
                        <div class="col-md-9">
                          <select id="country" class="form-control" name="country" required>
                            {% for country in countries %}
                              <option value="{{ country.pk }}" {% if object.country.pk == country.pk %}selected{% endif %}>
                                {{ country.name }}
                              </option>
                            {% endfor %}
                          </select>
                        </div>
                      </div>
                    </div>

                    <div class="col-md-6">
                      <div class="form-group row">
                        <label for="" class="col-md-3 col-form-label">{% trans "Region" %}</label>
                        <div class="col-md-9">
                          <select id="region" class="form-control" name="region" required>
                            <option value="">Seleccione</option>
                            {% for region in regions %}
                              <option value="{{ object.region.pk }}" {% if object.region.pk == region.pk %}selected{% endif %}>
                                {{ region.name }}
                              </option>
                            {% endfor %}
                          </select>
                        </div>
                      </div>
                    </div>

                    <div class="col-md-6">
                      <div class="form-group row">
                        <label for="" class="col-md-3 col-form-label">{% trans "City" %}</label>
                        <div class="col-md-9">
                          <select id="city" class="form-control" name="city">
                            <option value="">Seleccione</option>
                            {% for city in cities %}
                              <option value="{{ object.city.pk }}" {% if object.city.pk == city.pk %}selected{% endif %}>
                                {{ city.name }}
                              </option>
                            {% endfor %}
                          </select>
                        </div>
                      </div>
                    </div>

                    

                    <div class="col-md-6">
                      <div class="form-group row">
                        <label for="" class="col-md-3 col-form-label">{% trans "Role" %}</label>
                        <div class="col-md-9">
                          <select class="form-control" name="role" required="true" id="id_role">
                            <option value="">---------</option>
                            {% for rol in roles %}
                              <option value="{{ rol.pk }}"
                                {% if object.role == rol %}selected{% endif %}
                              >
                                {{ rol.name }}
                              </option>
                            {% endfor %}
                          </select>
                        </div>
                      </div>
                    </div>

                    <div class="col-md-6">
                      <div class="form-group row">
                        <label for="" class="col-md-3 col-form-label">{% trans "Sub-role" %}</label>
                        <div class="col-md-9">
                          <select class="form-control" name="group" id="id_group">
                            <option value="">---------</option>
                            {% for group in groups %}
                              <option value="{{ group.pk }}"

                                {% if group_selected == group %}selected{% endif %}
                              >
                                {{ group.name }}
                              </option>
                            {% endfor %}
                          </select>
                        </div>
                      </div>
                    </div>

                  </div>

                  <hr>
                  <div class="col-md-6">
                    <div class="form-group row">
                      <label for="" class="col-md-3 col-form-label">{% trans "Company" %}</label>
                      <div class="col-md-9">
                        {% render_field form.company  class="form-control" %}
                        {% for error in form.company.errors %}
                          <p class="text-danger">{{ error }}</p>
                        {% endfor %}
                      </div>
                    </div>
                  </div>
                  <button type="submit" class="btn btn-primary mr-2" name="button">{% trans "Save" %}</button>
                  <a href="{% url 'user-list' %}" class="btn btn-default">{% trans "Back" %}</a>
                </form>
              </div>

            </div>
            <!-- /.tab-content -->
          </div><!-- /.card-body -->
        </div>
        <!-- /.nav-tabs-custom -->
      </div>
      <!-- /.col -->
    </div>
  </div><!-- /.container-fluid -->
</section>
<!-- /.content -->
{% endblock %}

{% block extra_js %}
<script src="{% static 'adminlte-3.1.0/plugins/bootstrap-switch/js/bootstrap-switch.min.js' %}"></script>

<script type="text/javascript">
  $("input[data-bootstrap-switch]").each(function(){
    $(this).bootstrapSwitch('state', $(this).prop('checked'));
  });

  const select_country = document.getElementById('country');
  const select_region = document.getElementById('region');
  const select_city = document.getElementById('city');
  const select_role = document.getElementById('id_role');
  const select_subrole = document.getElementById('id_group');

  if (select_region) {
    select_region.addEventListener('change', (e) => {
      let country_id = select_country.value;
      let region_id = e.target.value;
      if (country_id && region_id) {
        display_cities(country_id, region_id);
      }
    });
  }

  if (select_country) {
    select_country.addEventListener('change', (e) => {
      let country_id = e.target.value;
      if (country_id) {
        display_regions(country_id);
      }
    });
  }

  function display_regions(country_id) {
    select_region.textContent = '';
    get_regions(country_id)
      .then(regions => {
        let first_region = regions[0].id;
        display_cities(country_id, first_region);

        regions.forEach((region, i) => {
          let option = document.createElement('option');
          option.value = region['id'];
          option.innerHTML = region['name'];
          select_region.appendChild(option);
        });
      })
      .catch( err => {
        select_city.textContent = '';
        console.warn(err)
      });
  }

  function display_cities(country_id, region_id) {
    select_city.textContent = '';
    get_cities(country_id, region_id)
      .then(cities => {
        cities.forEach((city, i) => {
          let option = document.createElement('option');
          option.value = city['id'];
          option.innerHTML = city['name'];
          select_city.appendChild(option);
        });

      })
      .catch( err => console.warn(err) );

  }


  if (select_role){
    select_role.addEventListener('change', (e) => {
      let role_id = e.target.value
      if (role_id){
        display_subroles(role_id)
      }
    });
  }

  function display_subroles(role_id){
    select_subrole.textContent = ''
    get_subroles(role_id) 
      .then(subroles => {
        subroles.forEach((role, i) => {
          let option = document.createElement('option');
          option.value = role['id'];
          option.innerHTML = role['name'];
          select_subrole.appendChild(option);
        });
    })
    .catch( err => console.warn(err) );
  }

  const get_subroles = async (role_id) => {
    const url = Urls.subrole_apilist(role_id);
    const response = await fetch(url, {
      method: 'get',
    });
    return response.json();
  }

</script>
{% endblock %}