apps/user/urls.py
from django.urls import  path
from rest_framework import routers

from .views.user_views import ( MeApiView, UserCreateApiView, UserListApiView, UserDetailApiView,
                PasswordResetView, PasswordResetDoneView, UserUpdateApiView, ListCollaboratorsApi )

from .views.user_views import (UserListView, UserAddView, UserDetailView, UserUpdateView, UserListExportView)
from .views.user_views import (UserDeleteView, UserDeactivateView, UserDestroy)

from .views.roles_views import RoleListView, RoleAddView, RoleDetailView, RoleUpdateView, RoleDeleteView

from .views.subrole_views import (SubroleListView, SubroleCreateView, SubroleDetailView, SubroleUpdateView)

from .views.roles_views import RoleApiListView

from .views.subrole_views import SubRoleApiListView, SubRolePermissionsApiListView


router = routers.SimpleRouter()

# router.register('', UserViewSet, basename='urls_user')


urlpatterns = [
    # ========================  Api User Endpoints  ===============================
    path('me/', MeApiView.as_view()),
    path('list/', UserListApiView.as_view()),
    path('create/', UserCreateApiView.as_view()),
    path('view/<int:pk>/', UserDetailApiView.as_view()),
    path('update/<int:pk>/', UserUpdateApiView.as_view()),
    path('password/reset/', PasswordResetView.as_view()),
    path('password/reset/done/<slug:slug>/', PasswordResetDoneView.as_view()),
    path('delete/', UserDeleteView.as_view(), name=UserDeleteView.url_name),
    path('deactivate/', UserDeactivateView.as_view(), name=UserDeactivateView.url_name),
    path('destroy-api/<int:pk>/', UserDestroy.as_view()),
    path('collaborators/', ListCollaboratorsApi.as_view()),


    # ============================= Templates Views User =================================
    path('viewlist/', UserListView.as_view(), name=UserListView.url_name),
    path('list/export/', UserListExportView.as_view(), name=UserListExportView.url_name),
    path('viewcreate/', UserAddView.as_view(), name=UserAddView.url_name),
    path('view/<int:pk>/detail/', UserDetailView.as_view(), name=UserDetailView.url_name),
    path('view/<int:pk>/update/', UserUpdateView.as_view(), name=UserUpdateView.url_name),

    # ============================= Templates Views Role =================================
    path('role/list/', RoleListView.as_view(), name=RoleListView.url_name),
    path('role/create/', RoleAddView.as_view(), name=RoleAddView.url_name),
    path('role/<int:pk>/detail/', RoleDetailView.as_view(), name=RoleDetailView.url_name),
    path('role/<int:pk>/update/', RoleUpdateView.as_view(), name=RoleUpdateView.url_name),
    path('role/delete/', RoleDeleteView.as_view(), name=RoleDeleteView.url_name),


    # ============================= Templates Views SubRole extends from GROUP ===========
    path('subrole/list/', SubroleListView.as_view(), name=SubroleListView.url_name),
    path('subrole/create/', SubroleCreateView.as_view(), name=SubroleCreateView.url_name),
    path('subrole/<int:pk>/detail/', SubroleDetailView.as_view(), name=SubroleDetailView.url_name),
    path('subrole/<int:pk>/update/', SubroleUpdateView.as_view(), name=SubroleUpdateView.url_name),
    
    # ============================= API Views SubRole  ==================================
    path('role/api/list/', RoleApiListView.as_view(), name="role-apilist"),
    path('subrole/api/list/<int:role_id>/', SubRoleApiListView.as_view(), name="subrole-apilist"), #BACKOFFICE
    path('subrole/permissions/api/list/<int:pk>/', SubRolePermissionsApiListView.as_view(), name="subrole-permissions-apilist"), #BACKOFFICE


]

urlpatterns += router.urls

config/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import  include, path

from apps.dashboard import urls as dashboard_urls
from apps.company import urls as company_urls
from apps.coordinates import urls as coordinates_urls
from apps.formulario import urls as formulario_urls
from apps.proforestform import urls as proforestform_urls
from apps.questionsbank import urls as questionbank_urls
from apps.traceability import urls as traceability_urls
from apps.supplybase import urls as supplybase_urls
from apps.user import urls as user_urls
from apps.onedrive import urls as onedrive_urls
from apps.emailcustom import urls as emailcustom_urls


from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)


urlpatterns = [
    #admin de Django
    path('adminproforest/', admin.site.urls), 


    #Include Auth urls
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    
    #Include dashboard app
    path('', include(dashboard_urls)),

    #Include Urls of Company APP
    path('company/', include(company_urls)),

    #Include Urls of Question Bank
    path('questionbank/', include (questionbank_urls)),

    #Include Urls of ProforestForm
    path('proforestform/', include (proforestform_urls)),

    #Include Urls of Formularios
    path('formulario/', include (formulario_urls)),
    #Include Traceability URLS

    path('traceability/', include (traceability_urls)),

    #Include User custom Urls
    path('users/', include(user_urls)),

    #Include Cities app Urls
    path('cities/', include('apps.cities.urls')),

    #Coordinates Validate Views
    path('coordinates/', include(coordinates_urls)),

    #Dependency Supply Base
    path('supplybase/', include(supplybase_urls)),

    #Email Template Views
    path('email/', include(emailcustom_urls)),

    #Landing for onedrive Oauth2
    path('onedrive/', include(onedrive_urls)),


    #Generic auth Views
    path('auth/login/',  auth_views.LoginView.as_view( template_name='adminlte/base/login.html' ), name='login'),
    path('auth/logout/', auth_views.logout_then_login, name='logout'),

    #HelperView to change Language
    path('i18n/', include('django.conf.urls.i18n'))

]

apps/user/models.py
from apps.user.views.groups import Check_user_in_groups

from cities_light.models import Country, Region, SubRegion
from config import settings

from apps.utils.models import base_model
from django.contrib.auth.models import (AbstractUser, BaseUserManager, Group)
from django.db import models
from django.dispatch import receiver
from django.core.mail import EmailMessage
from django.db.models.signals import pre_save, post_save
from django.template.loader import render_to_string
from django.utils.translation import gettext_lazy as _


import uuid
import random


class Role(base_model.BaseModel):
    name = models.CharField(max_length=126)
    groups = models.ManyToManyField(
        Group,
        blank = True,
    )
    class Meta:
        ordering = ['name']

    def __str__(self):
        return str(self.name)

class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('Users require an email field')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):

        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)

class User(AbstractUser,):
    username = None
    last_name = None
    email = models.EmailField('email address', unique=True)
    USERNAME_FIELD = 'email'
    """Use the email as unique username."""
    REQUIRED_FIELDS = ['first_name', 'surname']
    first_name = models.CharField(max_length=128)
    second_name = models.CharField(max_length=128, blank=True)
    surname = models.CharField(max_length=128)
    second_surname = models.CharField(max_length=128, blank=True)
    image_profile = models.ImageField(
        upload_to = 'user-profile/img/',
        null = True,
        blank = True,
    )
    created_date = models.DateTimeField(auto_now_add=True)
    role = models.ForeignKey(
        Role,
        on_delete = models.PROTECT,
        null = True,
        blank = True,
    )
    #Contact Info
    company = models.ForeignKey(
        'company.Company',
        on_delete = models.PROTECT,
        blank=True,
        null=True,
    )
    indicative = models.CharField(max_length=16)
    phone = models.CharField(max_length=16)
    country = models.ForeignKey(
        Country,
        on_delete=models.PROTECT,
        blank=True,
        null=True
        )
    region = models.ForeignKey(
        Region,
        on_delete=models.PROTECT,
        blank=True,
        null=True
    )
    city = models.ForeignKey(
        SubRegion,
        on_delete=models.PROTECT,
        blank=True,
        null=True
    )
    accept_terms_conditions = models.BooleanField(default=False)
    accept_terms_date = models.DateTimeField(blank=True, null=True)
    status = models.BooleanField(default=True)

    objects = UserManager()

    class Meta:
        ordering = ['pk']
        permissions=[
            ("change_own_user", "Can change own user")]
        

    def password_reset_mail(self, password_reset_slug:str ) -> None:
        url_password_reset_done = f'{settings.URL_PASSWORD_RESET}{password_reset_slug}'

        email_info = {
            'subject': 'Proforest - Restaurar contraseña.',
            'template': 'password_reset',
            'to': [self.email],
            'context': {
                'user': f'{self.first_name} {self.second_name}' if self.first_name else self.email,
                'url_password_reset_done': url_password_reset_done,
                
            },
        }

        self.send_mail(**email_info)

    def verify_email(self):
        email_info = {
            'subject': 'Proforest - Confirmación de cuenta.',
            'template': 'initial_verify_email',
            'to': [self.email],
            'context': {
                'user': f'{self.first_name} {self.second_name}' if self.first_name else self.email,
                'token': self.slug
            },
        }

        self.send_mail(**email_info)

    def send_mail(self, subject: str, to: list, template: str, context: dict) -> None:
        body = render_to_string(
            f'mail/{template}.html',
            context
        )
        email_message = EmailMessage(
            **{
                'subject': subject,
                'from_email': settings.EMAIL_FROM_DIR,
                'to': to,
                'body': body
            }
        )

        email_message.content_subtype = 'html'
        email_message.send()
    
    def get_full_name(self) -> str:
        return ' '.join((self.first_name, self.second_name, self.surname, self.second_surname))

    def get_image_profile_url(self):
        if self.image_profile:
            return self.image_profile.url
        else:
            return ''
    
    def get_country_display(self):
        if self.country:
            
            return self.country.name
        return _('No Register')

    def get_region_display(self):
        if self.region:
            return self.region.name
        return _('No Register')

    def get_city_display(self):
        if self.city:
            return self.city.name
        return _('No Register')

   

@receiver(post_save, sender=User)
def update_company_asociated(sender, **kwargs):
    from apps.company.models.company import Company #avoid circular importation
    instance = kwargs.get('instance')
    if instance.company:
        update_company = instance.company
        update_company.has_responsable = True
        update_company.save()
    try:
        groups = ['SUPERUSUARIO']
        if Check_user_in_groups(instance, groups):
            
            update_company = instance.company
            update_company.has_superuser = True
            update_company.save()
    except:
        pass #No company
    if instance.status == True:
        instance.is_active = True
    else :
        instance.is_active = False
    return

@receiver(pre_save, sender=User)
def update_company_asociated(sender, **kwargs):
    instance = kwargs.get('instance')
   
    if instance.status == True:
        instance.is_active = True
    else :
        instance.is_active = False
    return

class PasswordReset(base_model.BaseModel):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True, blank=True)
    recovery_code = models.IntegerField(blank=True,null=True)

    def get_recovery_code_str(self):
        str_recovery_code = ''
        for l in str(self.recovery_code):
            str_recovery_code += f'{l}'

        return str_recovery_code.strip()

@receiver(pre_save, sender=PasswordReset)
def slug_handler(sender, **kwargs):
    instance = kwargs.get('instance')

    if not instance.slug:
        for _ in range(16):
            slug = uuid.uuid4()

            if not sender.objects.filter(slug=slug).exists():
                instance.slug = slug
                return

apps/user/views/groups.py
from django.db.models import Q

def Check_user_in_groups(user, groups):
    return user.groups.filter(Q(name__in=groups)).exists()

apps/user/templates/user/role/role_create.html
{% extends 'adminlte/base/base.html' %}
{% load static i18n %}
{% load widget_tweaks %}

{% block extra_css %}
{% endblock %}

{% block content %}
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">{% trans "Create" %} {% trans "Role" %}</h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="{% url 'proforest-dashboard1' %}">{% trans "Home" %}</a></li>
          <li class="breadcrumb-item"><a href="{% url 'role-list' %}">{% trans "Role" %}</a></li>
          <li class="breadcrumb-item active">{% trans "Create" %}</li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <!-- /.col -->
      <div class="col-md-12">
        <div class="card">
          <div class="card-header p-2">
            <ul class="nav nav-pills">
              <li class="nav-item"><a class="nav-link active" href="#general" data-toggle="tab">{% trans "General information" %}</a></li>
            </ul>
          </div><!-- /.card-header -->
          <div class="card-body">
            <div class="tab-content">
              <div class="active tab-pane" id="general">
                <form class="form-horizontal" action="" method="post">
                  {% csrf_token %}
                  <div class="row">
                    <div class="col-md-6">
                      <div class="form-group row">
                        <label for="" class="col-md-3 col-form-label">{% trans "Name" %} {% trans "Role" %}</label>
                        <div class="col-md-9">
                          {% render_field form.name  class="form-control" %}
                          {% for error in form.name.errors %}
                            <p class="text-danger">{{ error }}</p>
                          {% endfor %}
                        </div>
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group row">
                        <label for="" class="col-md-3 col-form-label">{% trans "Sub-role" %}</label>
                        <div class="col-md-9">
                          {% render_field form.groups  class="form-control" %}
                          {% for error in form.groups.errors %}
                            <p class="text-danger">{{ error }}</p>
                          {% endfor %}
                        </div>
                      </div>
                    </div>
                  </div>

                  
                  <hr>
                  
                  <div class="row mt-3">
                    <button type="submit" class="btn btn-primary mr-2" name="button">{% trans "Save" %}</button>
                    <a href="{% url 'role-list'  %}" class="btn btn-default">{% trans "Back" %}</a>

                  </div>
                </form>
              </div>

            </div>
            <!-- /.tab-content -->
          </div><!-- /.card-body -->
        </div>
        <!-- /.nav-tabs-custom -->
      </div>
      <!-- /.col -->
    </div>
  </div><!-- /.container-fluid -->
</section>
<!-- /.content -->
{% endblock %}

{% block extra_js %}
<script src="{% static 'adminlte-3.1.0/plugins/bootstrap-switch/js/bootstrap-switch.min.js' %}"></script>

<script type="text/javascript">
  $("input[data-bootstrap-switch]").each(function(){
    $(this).bootstrapSwitch('state', $(this).prop('checked'));
  });


</script>
{% endblock %}

apps/user/templates/user/role/role_list.html
{% extends 'adminlte/base/base.html' %}
{% load static i18n %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'adminlte-3.1.0/plugins/select2/css/select2.min.css' %}">
<link rel="stylesheet" href="{% static 'adminlte-3.1.0/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css' %}">

<style media="screen">
  #_action_file_format{
    display: none;
  }
  #_action_file_format.active{
    display: block;
  }
</style>
{% endblock %}

{% block content %}
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">{% trans "Role" %}</h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="{% url 'proforest-dashboard1' %}">{% trans "home" %}</a></li>
          <li class="breadcrumb-item active">{% trans "Role" %}</li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
  <div class="container-fluid">
    <div class="card">
      <div class="card-header">
        <div class="card-tools">
          <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
            <i class="fas fa-minus"></i></button>
          <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
            <i class="fas fa-times"></i></button>
        </div>
      </div>
      <div class="card-body p-0">
        <form action="" method="get">
          <div class="row p-2">
            <div class="col-sm-12 col-md-6 mt-1">
              <!-- <input type="text" class="form-control" name="filter" value="{{ filter }}" placeholder="usuario, email"> -->
              <select class="select2" multiple="multiple" name="filter" style="width: 100%">
                {% if filter_obj.value %}
                  {% for filter in filter_obj.value %}
                    <option value="{{ filter }}" selected>{{ filter }}</option>
                  {% endfor %}
                {% endif %}
              </select>
            </div>

            <div class="col-sm-12 col-md-6 mt-1">
              <button type="submit" class="btn btn-primary ml-2">{% trans "Filter" %}</button>
              {% if perms.role.add_role %}
                <a href="{% url 'role-add' %}" class="btn btn-primary">{% trans "Add" %}</a>
              {% endif %}
              {% if filter_obj.url %}
                <a href="{% url 'role-list' %}" class="btn btn-warning">{% trans "Clear Filter" %}</a>
              {% endif %}
            </div>

          </div>
          <div class="row p-2">
            
          </div>
        </form>

        <form id="action-list-form" class="" action="{#% url 'user-list-export' %#}" method="post">{% csrf_token %}
          <input id="_selected_all_elements" type="hidden" name="selected-all-elements" value="0">
          <input id="_action" type="hidden" name="_action" value="">
          <input id="_format" type="hidden" name="_format_file" value="">
          <input id="_filter_verified" type="hidden" name="filter_verified" value="{{ filter_verified }}">

          {% if filter_obj.value %}
            {% for filter in filter_obj.value %}
              <input type="hidden" name="filter" value="{{ filter }}">
            {% endfor %}
          {% endif %}

          <table class="table table-striped table-responsive projects">
            <thead>
              <tr>
                <th class="" style="width: 1%">
                  <input id="_action_selection_page" class="" type="checkbox"
                    name="" value="">
                </th>
                <th class="">{% trans "Name" %}</th>
                <th class="text-center">{% trans "Actions" %}</th>
              </tr>
            </thead>
            <tbody>
              {% for object in object_list %}
                <tr>
                  <td>
                    <input class="form-checked-input" type="checkbox"
                      name="_action_selection" value="{{ object.pk }}">
                  </td>
                  <td>{{ object.name }}</td>
                  
                  <td class="text-center">
                    <a href="{% url 'role-detail' object.pk %}" class="ml-2"> <i class="far fa-eye nav-icon"></i> </a>
                    <a href="{% url 'role-update' object.pk %}" class="ml-2"> <i class="far fa-edit nav-icon"></i> </a>
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </form>
      </div>
      <!-- /.card-body -->

      <div class="card-footer">

        <div class="dataTables_paginate paging_simple_numbers">
          <ul class="float-left">
            <span style="font-weight: bold;">{% trans "Total" %}: {{ page_obj.paginator.count }}</span>
          </ul>
          <ul class="pagination float-right">
            {% if page_obj.has_previous %}
              <li class="paginate_button page-item"><a class="page-link"
                  href="?page=1{{filter_obj.url}}">«</a>
              </li>
              <li class="paginate_button page-item"><a class="page-link"
                  href="?page={{ page_obj.previous_page_number }}{{filter_obj.url}}">{% trans "Previous" %}</a>
              </li>
            {% endif %}

            {% for i in pages %}
              {% if page_obj.number == i %}
              <li class="paginate_button page-item">
                <a class="page-link" href="javascript:;">
                  {% trans "Page" %} {{ page_obj.number }} {% trans "of" %} {{ page_obj.paginator.num_pages }}.
                </a>
              </li>
              {% else %}
              <li class="paginate_button page-item">
                <a class="page-link" href="?page={{i}}{{filter_obj.url}}">
                  {{i}}
                </a>
              </li>
              {% endif %}

            {% endfor %}
            
            

            {% if page_obj.has_next %}
              <li class="paginate_button page-item"><a class="page-link"
                  href="?page={{ page_obj.next_page_number }}{{filter_obj.url}}">{% trans "Next" %}</a>
              </li>
              <li class="paginate_button page-item"><a class="page-link"
                  href="?page={{ page_obj.paginator.num_pages }}{{filter_obj.url}}">»</a>
              </li>
            {% endif %}

          </ul>
        </div>

      </div>
    </div>
  </div><!-- /.container-fluid -->
</section>
<!-- /.content -->
{% endblock %}

{% block extra_js %}
<script src="{% static 'adminlte-3.1.0/plugins/select2/js/select2.full.min.js' %}"></script>
<script src="{% static 'apps/core/js/actions.js' %}"></script>
<script type="text/javascript">

  $(function () {
    $('.select2').select2({
      placeholder: '{% trans "Name" %}',
      tags: true,
      tokenSeparators: [',']
    });
  });
</script>
{% endblock %}

apps/user/templates/user/role/role_update.html
{% extends 'adminlte/base/base.html' %}
{% load static i18n %}
{% load widget_tweaks %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'adminlte-3.1.0/plugins/sweetalert2/sweetalert2.min.css' %}">

{% endblock %}

{% block content %}
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">{% trans "Update" %} {% trans "Role" %}</h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="{% url 'proforest-dashboard1' %}">{% trans "Home" %}</a></li>
          <li class="breadcrumb-item"><a href="{% url 'role-list' %}">{% trans "Role" %}</a></li>
          <li class="breadcrumb-item active">{% trans "Update" %}</li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <!-- /.col -->
      <div class="col-md-12">
        <div class="card">
          <div class="card-header p-2">
            <ul class="nav nav-pills">
              <li class="nav-item"><a class="nav-link active" href="#general" data-toggle="tab">{% trans "General information" %}</a></li>
            </ul>
          </div><!-- /.card-header -->
          <form class="form-horizontal" method="post">
            <div class="card-body">
              <div class="tab-content">
                <div class="active tab-pane" id="general">
                    {% csrf_token %}
                    <div class="row">
                      <div class="col-md-6">
                        <div class="form-group row">
                          <label for="" class="col-md-3 col-form-label">{% trans "Name" %}</label>
                          <div class="col-md-9">
                            {% render_field form.name  class="form-control" %}
                            {% for error in form.name.errors %}
                              <p class="text-danger">{{ error }}</p>
                            {% endfor %}
                          </div>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="form-group row">
                          <label for="" class="col-md-3 col-form-label">{% trans "Sub-role" %}</label>
                          <div class="col-md-9">
                            {% render_field form.groups  class="form-control" %}
                            {% for error in form.groups.errors %}
                              <p class="text-danger">{{ error }}</p>
                            {% endfor %}
                          </div>
                        </div>
                      </div>
                    </div>

                </div>

              </div>
              <!-- /.tab-content -->
            </div><!-- /.card-body -->
          

            <div class="card-footer"> <!-- /.card-footer -->
              <button type="submit" class="btn btn-primary mr-2" name="button">{% trans "Save" %}</button>
              <a href="{% url 'role-list'  %}" class="btn btn-default">{% trans "Back" %}</a>
              <a href="#" onclick="delete_function('{{object.pk}}')" class="btn btn-danger float-right " >{% trans "Delete" %}</a>

            </div><!-- /.card-footer -->
        </form>
        </div>
        <!-- /.nav-tabs-custom -->
      </div>
      <!-- /.col -->
    </div>
  </div><!-- /.container-fluid -->
</section>
<!-- /.content -->
{% endblock %}

{% block extra_js %}
<script src="{% static 'adminlte-3.1.0/plugins/sweetalert2/sweetalert2.min.js' %}"></script>

<script type="text/javascript">

{% if perms.user.delete_role %}

function  delete_function(role_pk) {
  Swal.fire({
    title: '{% trans "Removal Process" %}',
    text: '{% trans "Please confirm if you want to delete the user." %}',
    icon: 'warning',
    showCancelButton: true,
    confirmButtonText: '{% trans "Delete" %}',
    confirmButtonColor: '#ff0000',
  }).then((result) => {
    if (result.isConfirmed) {
      delete_role(role_pk);
    }
  })
}

function delete_role (role_pk, action, notes='') {

  let form_data = new FormData();
  form_data.append("pk", role_pk);
  form_data.append('csrfmiddlewaretoken', '{{ csrf_token }}');
  url = Urls.role_delete();
  fetch(url, {
    method: 'post',
    body: form_data,
  })
  .then((response) => {
    return response.json();
  })
  .then((data) => {
    if (data['status'] == 'success') {
      Swal.fire({
        title: `${data['title']}`,
        text: `${data['message']}`,
        icon: 'success',
        showConfirmButton: false,
        timer: 2000
      }).then((result) => {
        window.location.replace('/users/role/list/');
      });
    }else{
      Swal.fire({
        title: `${data['title']}`,
        text: data['message'],
        icon: 'error',
        showConfirmButton: false,
        timer: 2000
      });
    }
  })
  .catch((error) => {
    Swal.fire({
      title: '{% trans "Error changing state"  %}',
      text: '{% trans "Error processing the request, Contact your Administrator!"  %}',
      icon: 'error',
      confirmButtonText: "Cerrar",
      confirmButtonColor: '#6e7d88',
    });
  });
}
{% endif %}

</script>
{% endblock %}