apps/supplybase/urls.py
from django.urls import path
from .views import backoffice_views, supplybase_views

urlpatterns = [
    # ========================  SupplyBase Backoffice  ===============================

    path('list/', backoffice_views.SupplybasedependencyList.as_view(),
        name=backoffice_views.SupplybasedependencyList.url_name),
    path('create/', backoffice_views.SupplybasedependencyCreate.as_view(),
        name=backoffice_views.SupplybasedependencyCreate.url_name),
    path('update/<int:pk>/', backoffice_views.SupplybasedependencyUpdate.as_view(),
        name=backoffice_views.SupplybasedependencyUpdate.url_name),
    
    # ========================  SuppliBase Endpoints  ===============================

    path('api/list/', supplybase_views.SupplyBaseRegisterList.as_view()),
    path('api/getdependencies/', supplybase_views.SupplyBaseGetDependency.as_view()),
    path('api/checkregister/', supplybase_views.CheckSupplyBaseRegister.as_view()),
    path('api/create/', supplybase_views.SupplyBaseCreate.as_view()),
    path('api/detail/<int:pk>/', supplybase_views.SupplyBaseDetailView.as_view()),

    path('api/obtainsupplybase/location/', supplybase_views.ObtainSupplyBaseRegistersLocation.as_view()),
    path('api/detail/compareview/<int:pk>/', supplybase_views.SupplyBaseTotalResumeView.as_view()),
    path('api/update/purchasedpercentage/<int:pk>/', supplybase_views.PurchasedPercentageUpdateView.as_view()),


]

config/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import  include, path

from apps.dashboard import urls as dashboard_urls
from apps.company import urls as company_urls
from apps.coordinates import urls as coordinates_urls
from apps.formulario import urls as formulario_urls
from apps.proforestform import urls as proforestform_urls
from apps.questionsbank import urls as questionbank_urls
from apps.traceability import urls as traceability_urls
from apps.supplybase import urls as supplybase_urls
from apps.user import urls as user_urls
from apps.onedrive import urls as onedrive_urls
from apps.emailcustom import urls as emailcustom_urls


from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)


urlpatterns = [
    #admin de Django
    path('adminproforest/', admin.site.urls), 


    #Include Auth urls
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    
    #Include dashboard app
    path('', include(dashboard_urls)),

    #Include Urls of Company APP
    path('company/', include(company_urls)),

    #Include Urls of Question Bank
    path('questionbank/', include (questionbank_urls)),

    #Include Urls of ProforestForm
    path('proforestform/', include (proforestform_urls)),

    #Include Urls of Formularios
    path('formulario/', include (formulario_urls)),
    #Include Traceability URLS

    path('traceability/', include (traceability_urls)),

    #Include User custom Urls
    path('users/', include(user_urls)),

    #Include Cities app Urls
    path('cities/', include('apps.cities.urls')),

    #Coordinates Validate Views
    path('coordinates/', include(coordinates_urls)),

    #Dependency Supply Base
    path('supplybase/', include(supplybase_urls)),

    #Email Template Views
    path('email/', include(emailcustom_urls)),

    #Landing for onedrive Oauth2
    path('onedrive/', include(onedrive_urls)),


    #Generic auth Views
    path('auth/login/',  auth_views.LoginView.as_view( template_name='adminlte/base/login.html' ), name='login'),
    path('auth/logout/', auth_views.logout_then_login, name='logout'),

    #HelperView to change Language
    path('i18n/', include('django.conf.urls.i18n'))

]

apps/supplybase/models/supplybase.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

from apps.user.models import User
from apps.company.models.company import Company
from apps.proforestform.models.proforestform import ProforestForm
from apps.company.models.actor_type import ActorType


class SupplyBase (models.Model):
    company = models.ForeignKey(
        Company,
        on_delete = models.PROTECT,
        related_name='supplybase_company',
    )
    supplier_company = models.ForeignKey(
        Company,
        on_delete = models.PROTECT,
        related_name='supplybase_supplier_company',
    )

    created = models.DateTimeField(auto_now_add=True)

    def get_some_fill_form(self):
        #Search if supplier company has filled forms
        if ProforestForm.objects.filter(assigned_company=self.supplier_company, revision_status='CHECK' ).exists():
            return True
        else:
            return False

    def get_fill_form_for_my_company(self):
        #Search if supplier company has filled my sended forms

        if ProforestForm.objects.filter(
                    allocating_company=self.company,
                    assigned_company=self.supplier_company,
                    revision_status='CHECK' ).exists():
            return True
        else:
            return False

class SupplyBaseDependency (models.Model):
    actor_type = models.OneToOneField(
        ActorType,
        on_delete=models.PROTECT,
        related_name='actortype_buyer',
    )
    actor_type_dependency = models.ManyToManyField(ActorType)

class SupplyBaseRegister(models.Model):
    created_by = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name='register_by')
    company = models.ForeignKey(
        Company,
        on_delete = models.PROTECT,
        related_name='reporting_company',
    )
    register_year =  models.IntegerField()
    period = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(2)])
    purchased_volume = models.FloatField(blank = True, null = True) #Lo que compro para ese periodo en volumen (toneladas)

    def __str__(self):
        return str(self.company) + ' Year: '+ str(self.register_year) +' period: '+ str(self.period)

class PurchasedPercentage(models.Model):
    supplybase_register = models.ForeignKey(
        SupplyBaseRegister,
        on_delete=models.PROTECT,
    )
    percentage = models.FloatField()
    actor_type = models.ForeignKey(
        ActorType,
        on_delete=models.PROTECT,
        related_name='supplier_actortype',
    )

apps/supplybase/views/backoffice_views.py
from apps.company.models.actor_type import ActorType
from apps.company.models.commodity import Commodity

from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required, permission_required
from django.views.generic import View, ListView, CreateView, DetailView, UpdateView
from django.db.models import Q
from django.urls import reverse_lazy
from django.utils import translation


from ..models.supplybase import SupplyBase, SupplyBaseDependency

# =============================================================================
#                           BACKOFFICE RESOURCE
# =============================================================================


@method_decorator(login_required, name='dispatch')
class SupplybasedependencyList(ListView):
    template_name = 'supplybase/supplybase_list.html'
    url_name = 'supplybase-dependency-list'
    model = SupplyBaseDependency
    paginate_by = 25

    def get_queryset(self):
        name_translate = 'name_'+ str(translation.get_language())
        filter_list = self.request.GET.getlist('filter')
        filters = Q()
        if (filter_list and filter_list != ''):
            for filter in filter_list:
                fields = [
                    'actor_type__'+name_translate+'__icontains',
                    'actor_type_dependency__'+name_translate+'__icontains',
                ]

                for str_field in fields:
                    filters |= Q(**{str_field: filter})
        queryset = SupplyBaseDependency.objects.filter(filters).order_by('-id')

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        filter_obj = {
            'value': [],
            'url': ''
        }

        filter_list = self.request.GET.getlist('filter')
        if (filter_list and filter_list != ''):
            for filter in filter_list:
                filter_obj['value'].append(
                    filter
                )
                filter_obj['url'] += '&filter={}'.format(filter)

        
        context['filter_obj'] = filter_obj
        context['nav_supplybasedependency'] = True

        paginator = context.get('paginator')
        num_pages = paginator.num_pages
        current_page = context.get('page_obj')
        page_no = current_page.number

        if num_pages <= 11 or page_no <= 6:  # case 1 and 2
            pages = [x for x in range(1, min(num_pages + 1, 12))]
        elif page_no > num_pages - 6:  # case 4
            pages = [x for x in range(num_pages - 10, num_pages + 1)]
        else:  # case 3
            pages = [x for x in range(page_no - 5, page_no + 6)]

        context.update({'pages': pages})
        return context
# =============================================================================

@method_decorator(login_required, name='dispatch')
@method_decorator(permission_required('company.add_supplybase', raise_exception=True), name='dispatch')
class SupplybasedependencyCreate(CreateView):
    template_name = 'supplybase/supplybase_create.html'
    url_name = 'supplybase-dependency-create'
    model = SupplyBaseDependency
    fields = '__all__'

    def get_success_url(self):
        return reverse_lazy("supplybase-dependency-list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        name_translate = 'name_'+ str(translation.get_language())
        commodities = Commodity.objects.filter(status=True)
        context['commodities'] = commodities
        optgroups = []

        for commodity in commodities:
            commodity_optgroup = {
                "label": getattr(commodity, name_translate),
                "options": []
            }
            dependencies = ActorType.objects.filter(status=True, commodity= commodity)
            
            for dependency in dependencies:
                commodity_optgroup["options"].append({
                    "value": dependency.id,
                    "name": getattr(dependency, name_translate),
                })
            optgroups.append(commodity_optgroup)
        context['optgroups'] = optgroups

        filter_translate = 'commodity__name_'+ str(translation.get_language())
        queryset = ActorType.objects.none()
        for commodity in commodities:
            queryset |= ActorType.objects.filter(status=True, commodity= commodity)
        context['actor_types'] = queryset.order_by(filter_translate)
        context['nav_supplybase'] = True

        return context
# =============================================================================

@method_decorator(login_required, name='dispatch')
@method_decorator(permission_required('company.change_supplybase', raise_exception=True), name='dispatch')
class SupplybasedependencyUpdate(UpdateView):
    template_name = 'supplybase/supplybase_update.html'
    url_name = 'supplybase-dependency-update'
    model = SupplyBaseDependency
    fields = [ 'actor_type_dependency']

    def get_success_url(self):
        pk = self.kwargs["pk"]
        return reverse_lazy("supplybase-dependency-list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        supplybaseDependency = SupplyBaseDependency.objects.get(pk=self.kwargs["pk"])
        name_translate = 'commodity__name_'+ str(translation.get_language())
        commodities = Commodity.objects.filter(status=True)
        queryset = ActorType.objects.none()
        for commodity in commodities:
            queryset |= ActorType.objects.filter(status=True, commodity= commodity)
        context['actor_types'] = queryset.order_by(name_translate)
        context['supplybaseDependency'] = supplybaseDependency
        context['dependencies'] = supplybaseDependency.actor_type_dependency.all()
        context['nav_supplybase'] = True
        return context

# =============================================================================

apps/supplybase/templates/supplybase/supplybase_create.html
{% extends 'adminlte/base/base.html' %}
{% load static i18n %}
{% load widget_tweaks %}

{% block extra_css %}
  <!-- Bootstrap4 Duallistbox -->
  <link rel="stylesheet" href="{% static 'adminlte-3.1.0/plugins/bootstrap4-duallistbox/bootstrap-duallistbox.min.css' %}">

{% endblock %}

{% block content %}
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">{% trans "Create" %} {% trans "Supply base dependency" %}</h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="{% url 'proforest-dashboard1' %}">{% trans "Home" %}</a></li>
          <li class="breadcrumb-item"><a href="{% url 'subrole-list' %}">{% trans "Supply base dependency" %}</a></li>
          <li class="breadcrumb-item active">{% trans "Create" %}</li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">

{% get_current_language as LANGUAGE_CODE %}

  <div class="container-fluid">
    <div class="row">
      <!-- /.col -->
      <div class="col-md-12">
        <div class="card">
          <div class="card-header p-2">
            <ul class="nav nav-pills">
              <li class="nav-item"><a class="nav-link active" href="#general" data-toggle="tab">{% trans "General information" %}</a></li>
            </ul>
          </div><!-- /.card-header -->
          <div class="card-body">
            <div class="tab-content">
              <div class="active tab-pane" id="general">
                <form class="form-horizontal" action="" method="post">
                  {% csrf_token %}
                  <div class="row">
                    <div class="col-md-6">
                      
                      <div class="form-group row">
                        <label for="" class="col-md-3 col-form-label">{% trans "Actor Type" %}</label>
                        <div class="col-md-9">
                          <select name="actor_type" class="form-control" required="" id="id_actor_type">
                            <option value="" selected="">---------</option>
                            {% for optgroup in optgroups %}
                              <optgroup label="{{optgroup.label}}">
                                {% for option in optgroup.options %}
                                  <option value="{{option.value}}">{{option.name}}</option>
                                {% endfor %}
                              </optgroup>
                            {% endfor %}
                          </select>
                          {% for error in form.actor_type.errors %}
                            <p class="text-danger">{{ error }}</p>
                          {% endfor %}
                        </div>
                      </div>
                    </div>
                  </div>

                  <div class="row">
                    <div class="col-12">
                      <div class="form-group">
                        <label>{% trans "Select Supply base dependency permissions" %}</label>
                          <select class="duallistbox" multiple="multiple" name="actor_type_dependency" id="id_actor_type_dependency">
                            {% for actor_type in actor_types %}
                                  <option value="{{actor_type.id}}"
                                  {% if actor_type in dependencies %}
                                  selected
                                  {% endif %}
                                  >
                                  {% if LANGUAGE_CODE == 'es' %}
                                    {{actor_type.commodity.name_es}} > {{actor_type.name_es}}
                                  {% elif LANGUAGE_CODE == 'en' %}
                                    {{actor_type.commodity.name_en}} > {{actor_type.name_en}}
                                  {% elif LANGUAGE_CODE == 'pt' %}
                                    {{actor_type.commodity.name_pt}} > {{actor_type.name_pt}}
                                  {% endif %}
                                  
                                  </option>
                                
                            {% endfor %}
                          </select>
                          
                      </div>
                    </div>
                  </div>
                  
                  <hr>
                  
                  <div class="row mt-3">
                    <button type="submit" class="btn btn-primary mr-2" name="button">{% trans "Save" %}</button>
                    <a href="{% url 'supplybase-dependency-list'  %}" class="btn btn-default">{% trans "Back" %}</a>
                  </div>
                </form>
              </div>

            </div>
            <!-- /.tab-content -->
          </div><!-- /.card-body -->
        </div>
        <!-- /.nav-tabs-custom -->
      </div>
      <!-- /.col -->
    </div>
  </div><!-- /.container-fluid -->
</section>
<!-- /.content -->
{% endblock %}

{% block extra_js %}
<script src="{% static 'adminlte-3.1.0/plugins/bootstrap-switch/js/bootstrap-switch.min.js' %}"></script>
<!-- Bootstrap4 Duallistbox -->
<script src="{% static 'adminlte-3.1.0/plugins/bootstrap4-duallistbox/jquery.bootstrap-duallistbox.min.js' %}"></script>

<script type="text/javascript">
  $("input[data-bootstrap-switch]").each(function(){
    $(this).bootstrapSwitch('state', $(this).prop('checked'));
  });

//Bootstrap Duallistbox
$('.duallistbox').bootstrapDualListbox()

</script>
{% endblock %}

apps/supplybase/templates/supplybase/supplybase_update.html
{% extends 'adminlte/base/base.html' %}
{% load static i18n %}
{% load widget_tweaks %}

{% block extra_css %}
  <!-- Bootstrap4 Duallistbox -->
  <link rel="stylesheet" href="{% static 'adminlte-3.1.0/plugins/bootstrap4-duallistbox/bootstrap-duallistbox.min.css' %}">

{% endblock %}

{% block content %}
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">{% trans "Create" %} {% trans "Supply base dependency" %}</h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="{% url 'proforest-dashboard1' %}">{% trans "Home" %}</a></li>
          <li class="breadcrumb-item"><a href="{% url 'subrole-list' %}">{% trans "Supply base dependency" %}</a></li>
          <li class="breadcrumb-item active">{% trans "Create" %}</li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">

{% get_current_language as LANGUAGE_CODE %}

  <div class="container-fluid">
    <div class="row">
      <!-- /.col -->
      <div class="col-md-12">
        <div class="card">
          <div class="card-header p-2">
            <ul class="nav nav-pills">
              <li class="nav-item"><a class="nav-link active" href="#general" data-toggle="tab">{% trans "General information" %}</a></li>
            </ul>
          </div><!-- /.card-header -->
          <div class="card-body">
            <div class="tab-content">
              <div class="active tab-pane" id="general">
                <form class="form-horizontal" action="" method="post">
                  {% csrf_token %}
                  <div class="row">
                    <div class="col-md-6">
                    
                      <div class="form-group row">
                        <label for="" class="col-md-3 col-form-label">{% trans "Actor Type" %}</label>
                        <div class="col-md-9">
                          <select name="actor_type" class="form-control" required="" id="id_actor_type">
                             <option value="{{supplybaseDependency.actor_type.id}}">
                              {% if LANGUAGE_CODE == 'es' %}
                                {{supplybaseDependency.actor_type.name_es}}
                              {% elif LANGUAGE_CODE == 'en' %}
                                {{supplybaseDependency.actor_type.name_en}}
                              {% elif LANGUAGE_CODE == 'pt' %}
                                {{supplybaseDependency.actor_type.name_pt}}
                              {% endif %}
                             
                             </option>
                          </select>
                          {% for error in form.actor_type.errors %}
                            <p class="text-danger">{{ error }}</p>
                          {% endfor %}
                        </div>
                      </div>
                    </div>
                  </div>

                  <div class="row">
                    <div class="col-12">
                      <div class="form-group">
                        <label>{% trans "Select Supply base dependency permissions" %}</label>
                          <select class="duallistbox" multiple="multiple" name="actor_type_dependency" id="id_actor_type_dependency">
                            {% for actor_type in actor_types %}
                                  <option value="{{actor_type.pk}}"
                                  {% if actor_type in dependencies %}
                                  selected
                                  {% endif %}
                                  >
                                  {% if LANGUAGE_CODE == 'es' %}
                                    {{actor_type.commodity.name_es}} > {{actor_type.name_es}}
                                  {% elif LANGUAGE_CODE == 'en' %}
                                    {{actor_type.commodity.name_en}} > {{actor_type.name_en}}
                                  {% elif LANGUAGE_CODE == 'pt' %}
                                    {{actor_type.commodity.name_pt}} > {{actor_type.name_pt}}
                                  {% endif %}
                                  
                                  </option>
                                
                            {% endfor %}
                          </select>
                      </div>
                    </div>
                  </div>
                  <hr>
                  
                  <div class="row mt-3">
                    <button type="submit" class="btn btn-primary mr-2" name="button">{% trans "Save" %}</button>
                    <a href="{% url 'supplybase-dependency-list'  %}" class="btn btn-default">{% trans "Back" %}</a>
                  </div>
                </form>
              </div>

            </div>
            <!-- /.tab-content -->
          </div><!-- /.card-body -->
        </div>
        <!-- /.nav-tabs-custom -->
      </div>
      <!-- /.col -->
    </div>
  </div><!-- /.container-fluid -->
</section>
<!-- /.content -->
{% endblock %}

{% block extra_js %}
<script src="{% static 'adminlte-3.1.0/plugins/bootstrap-switch/js/bootstrap-switch.min.js' %}"></script>
<!-- Bootstrap4 Duallistbox -->
<script src="{% static 'adminlte-3.1.0/plugins/bootstrap4-duallistbox/jquery.bootstrap-duallistbox.min.js' %}"></script>

<script type="text/javascript">
  $("input[data-bootstrap-switch]").each(function(){
    $(this).bootstrapSwitch('state', $(this).prop('checked'));
  });

//Bootstrap Duallistbox
$('.duallistbox').bootstrapDualListbox()

</script>
{% endblock %}