apps/dashboard/urls.py
from django.urls import path
from .views import Dashboard1View


urlpatterns = [
    # ============================= Templates Views ============================
    path('', Dashboard1View.as_view(), name=Dashboard1View.url_name),
]

config/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import  include, path

from apps.dashboard import urls as dashboard_urls
from apps.company import urls as company_urls
from apps.coordinates import urls as coordinates_urls
from apps.formulario import urls as formulario_urls
from apps.proforestform import urls as proforestform_urls
from apps.questionsbank import urls as questionbank_urls
from apps.traceability import urls as traceability_urls
from apps.supplybase import urls as supplybase_urls
from apps.user import urls as user_urls
from apps.onedrive import urls as onedrive_urls
from apps.emailcustom import urls as emailcustom_urls


from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)


urlpatterns = [
    #admin de Django
    path('adminproforest/', admin.site.urls), 


    #Include Auth urls
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    
    #Include dashboard app
    path('', include(dashboard_urls)),

    #Include Urls of Company APP
    path('company/', include(company_urls)),

    #Include Urls of Question Bank
    path('questionbank/', include (questionbank_urls)),

    #Include Urls of ProforestForm
    path('proforestform/', include (proforestform_urls)),

    #Include Urls of Formularios
    path('formulario/', include (formulario_urls)),
    #Include Traceability URLS

    path('traceability/', include (traceability_urls)),

    #Include User custom Urls
    path('users/', include(user_urls)),

    #Include Cities app Urls
    path('cities/', include('apps.cities.urls')),

    #Coordinates Validate Views
    path('coordinates/', include(coordinates_urls)),

    #Dependency Supply Base
    path('supplybase/', include(supplybase_urls)),

    #Email Template Views
    path('email/', include(emailcustom_urls)),

    #Landing for onedrive Oauth2
    path('onedrive/', include(onedrive_urls)),


    #Generic auth Views
    path('auth/login/',  auth_views.LoginView.as_view( template_name='adminlte/base/login.html' ), name='login'),
    path('auth/logout/', auth_views.logout_then_login, name='logout'),

    #HelperView to change Language
    path('i18n/', include('django.conf.urls.i18n'))

]

apps/dashboard/models.py
from django.db import models

# Create your models here.

apps/user/models.py
from apps.user.views.groups import Check_user_in_groups

from cities_light.models import Country, Region, SubRegion
from config import settings

from apps.utils.models import base_model
from django.contrib.auth.models import (AbstractUser, BaseUserManager, Group)
from django.db import models
from django.dispatch import receiver
from django.core.mail import EmailMessage
from django.db.models.signals import pre_save, post_save
from django.template.loader import render_to_string
from django.utils.translation import gettext_lazy as _


import uuid
import random


class Role(base_model.BaseModel):
    name = models.CharField(max_length=126)
    groups = models.ManyToManyField(
        Group,
        blank = True,
    )
    class Meta:
        ordering = ['name']

    def __str__(self):
        return str(self.name)

class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('Users require an email field')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):

        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)

class User(AbstractUser,):
    username = None
    last_name = None
    email = models.EmailField('email address', unique=True)
    USERNAME_FIELD = 'email'
    """Use the email as unique username."""
    REQUIRED_FIELDS = ['first_name', 'surname']
    first_name = models.CharField(max_length=128)
    second_name = models.CharField(max_length=128, blank=True)
    surname = models.CharField(max_length=128)
    second_surname = models.CharField(max_length=128, blank=True)
    image_profile = models.ImageField(
        upload_to = 'user-profile/img/',
        null = True,
        blank = True,
    )
    created_date = models.DateTimeField(auto_now_add=True)
    role = models.ForeignKey(
        Role,
        on_delete = models.PROTECT,
        null = True,
        blank = True,
    )
    #Contact Info
    company = models.ForeignKey(
        'company.Company',
        on_delete = models.PROTECT,
        blank=True,
        null=True,
    )
    indicative = models.CharField(max_length=16)
    phone = models.CharField(max_length=16)
    country = models.ForeignKey(
        Country,
        on_delete=models.PROTECT,
        blank=True,
        null=True
        )
    region = models.ForeignKey(
        Region,
        on_delete=models.PROTECT,
        blank=True,
        null=True
    )
    city = models.ForeignKey(
        SubRegion,
        on_delete=models.PROTECT,
        blank=True,
        null=True
    )
    accept_terms_conditions = models.BooleanField(default=False)
    accept_terms_date = models.DateTimeField(blank=True, null=True)
    status = models.BooleanField(default=True)

    objects = UserManager()

    class Meta:
        ordering = ['pk']
        permissions=[
            ("change_own_user", "Can change own user")]
        

    def password_reset_mail(self, password_reset_slug:str ) -> None:
        url_password_reset_done = f'{settings.URL_PASSWORD_RESET}{password_reset_slug}'

        email_info = {
            'subject': 'Proforest - Restaurar contraseña.',
            'template': 'password_reset',
            'to': [self.email],
            'context': {
                'user': f'{self.first_name} {self.second_name}' if self.first_name else self.email,
                'url_password_reset_done': url_password_reset_done,
                
            },
        }

        self.send_mail(**email_info)

    def verify_email(self):
        email_info = {
            'subject': 'Proforest - Confirmación de cuenta.',
            'template': 'initial_verify_email',
            'to': [self.email],
            'context': {
                'user': f'{self.first_name} {self.second_name}' if self.first_name else self.email,
                'token': self.slug
            },
        }

        self.send_mail(**email_info)

    def send_mail(self, subject: str, to: list, template: str, context: dict) -> None:
        body = render_to_string(
            f'mail/{template}.html',
            context
        )
        email_message = EmailMessage(
            **{
                'subject': subject,
                'from_email': settings.EMAIL_FROM_DIR,
                'to': to,
                'body': body
            }
        )

        email_message.content_subtype = 'html'
        email_message.send()
    
    def get_full_name(self) -> str:
        return ' '.join((self.first_name, self.second_name, self.surname, self.second_surname))

    def get_image_profile_url(self):
        if self.image_profile:
            return self.image_profile.url
        else:
            return ''
    
    def get_country_display(self):
        if self.country:
            
            return self.country.name
        return _('No Register')

    def get_region_display(self):
        if self.region:
            return self.region.name
        return _('No Register')

    def get_city_display(self):
        if self.city:
            return self.city.name
        return _('No Register')

   

@receiver(post_save, sender=User)
def update_company_asociated(sender, **kwargs):
    from apps.company.models.company import Company #avoid circular importation
    instance = kwargs.get('instance')
    if instance.company:
        update_company = instance.company
        update_company.has_responsable = True
        update_company.save()
    try:
        groups = ['SUPERUSUARIO']
        if Check_user_in_groups(instance, groups):
            
            update_company = instance.company
            update_company.has_superuser = True
            update_company.save()
    except:
        pass #No company
    if instance.status == True:
        instance.is_active = True
    else :
        instance.is_active = False
    return

@receiver(pre_save, sender=User)
def update_company_asociated(sender, **kwargs):
    instance = kwargs.get('instance')
   
    if instance.status == True:
        instance.is_active = True
    else :
        instance.is_active = False
    return

class PasswordReset(base_model.BaseModel):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True, blank=True)
    recovery_code = models.IntegerField(blank=True,null=True)

    def get_recovery_code_str(self):
        str_recovery_code = ''
        for l in str(self.recovery_code):
            str_recovery_code += f'{l}'

        return str_recovery_code.strip()

@receiver(pre_save, sender=PasswordReset)
def slug_handler(sender, **kwargs):
    instance = kwargs.get('instance')

    if not instance.slug:
        for _ in range(16):
            slug = uuid.uuid4()

            if not sender.objects.filter(slug=slug).exists():
                instance.slug = slug
                return

apps/dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import View
from django.shortcuts import redirect




@method_decorator(login_required, name='dispatch')
class Dashboard1View(View):
    template_name = 'dashboard_1.html'
    url_name = 'proforest-dashboard1'

    def get(self, request, *args, **kwargs):
        context = {}
        context['companies'] = "xxx"
        context['nav_inicio'] = True
        return render(request, self.template_name, context)
    
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            # This will redirect to the login view
            return self.handle_no_permission()
        if not self.request.user.is_superuser:
            # Redirect the user to somewhere else - add your URL here
            return redirect('/auth/logout/')

        # Checks pass, let http method handlers process the request
        return super().dispatch(request, *args, **kwargs)

apps/dashboard/templates/dashboard_1.html
{% extends 'adminlte/base/base.html' %}
{% load static i18n %}

{% block extra_css %}
{% endblock %}

{% block content %}
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">Dashboard 1</h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="{% url 'proforest-dashboard1' %}">Inicio</a></li>
          <li class="breadcrumb-item active">Dashboard 1</li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
  <div class="container-fluid">
    <!-- Info boxes -->
    <div class="row">
      <div class="col-12 col-sm-6 col-md-4">
        <div class="info-box mb-3">
          <span class="info-box-icon bg-info elevation-1"><i class="fas fa-users"></i></span>

          <div class="info-box-content">
            <span class="info-box-text">Empresas Registradas</span>
            <span class="info-box-number">{{ users_registered.count }}</span>
          </div>
          <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
      </div>
      <!-- /.col -->
      <div class="col-12 col-sm-6 col-md-4">
        <div class="info-box mb-3">
          <span class="info-box-icon bg-success elevation-1"><i class="fas fa-shopping-cart"></i></span>

          <div class="info-box-content">
            <span class="info-box-text">Total Trazabilidad</span>
            <span class="info-box-number">{{ transactions.count }}</span>
          </div>
          <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
      </div>
      <!-- /.col -->
      
      <!-- /.col -->
      <div class="col-12 col-sm-6 col-md-4">
        <div class="info-box mb-3">
          <span class="info-box-icon bg-warning elevation-1"><i class="fas fa-thumbs-up"></i></span>

          <div class="info-box-content">
            <span class="info-box-text">Pendientes por Validar</span>
            <span class="info-box-number">{{ transactions_pending.count }}</span>
          </div>
          <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
      </div>
      <!-- /.col -->

      <!-- fix for small devices only -->
      <div class="clearfix hidden-md-up"></div>

    </div>
    <!-- /.row -->


    <!-- Main row -->
    <div class="row">
      <!-- Left col -->
      <div class="col-md-8">
        <!-- TABLE: LATEST ORDERS -->
        <div class="card">
          <div class="card-header border-transparent">
            <h3 class="card-title">Ultimas Empresas Registradas</h3>

            <div class="card-tools">
              <button type="button" class="btn btn-tool" data-card-widget="collapse">
                <i class="fas fa-minus"></i>
              </button>
              <button type="button" class="btn btn-tool" data-card-widget="remove">
                <i class="fas fa-times"></i>
              </button>
            </div>
          </div>
          <!-- /.card-header -->
          <div class="card-body p-0">
            <div class="table-responsive">
              <table class="table m-0">
                <thead>
                  <tr>
                    <th>Nombre ID</th>
                    <th>Proforest ID</th>
                    <th>Responsable</th>
                    <th>Validador</th>
                    <th>%</th>
                  </tr>
                </thead>
                <tbody>
                  {% for transaction in transactions|slice:":8"%}
                    <tr>
                      <td>
                        {% if perms.wallet.view_wallettransaction %}
                          <a href="{% url 'proforest-dashboard1' transaction.pk %}">{{ transaction.slug }}</a>
                        {% else %}
                          {{ transaction.slug }}
                        {% endif %}
                      </td>
                      <td>{{ transaction.get_type_display }}</td>
                      <td>{{ transaction.sender.username }}</td>
                      <td>{{ transaction.amount }}</td>
                      <td>
                        {% if transaction.status %}
                          <span class="badge badge-success">Confirmado</span>
                        {% else %}
                          <span class="badge badge-warning">Pendiente</a>
                        {% endif %}
                      </td>
                      <td>{{ transaction.created_at }}</td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
            <!-- /.table-responsive -->
          </div>
          <!-- /.card-body -->
          <div class="card-footer clearfix">
            {% if perms.wallet.view_wallettransaction %}
              <a href="{% url 'proforest-dashboard1' %}" class="btn btn-sm btn-secondary float-right">Ver Todas</a>
            {% else %}
              <a href="#" class="btn btn-sm btn-secondary float-right disabled">Ver Todas</a>
            {% endif %}
          </div>
          <!-- /.card-footer -->
        </div>
        <!-- /.card -->
      </div>
      <!-- /.col -->

      <div class="col-md-4">

        <!-- USERS LIST -->
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Ultimos Usuarios</h3>

            <div class="card-tools">
              <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i>
              </button>
              <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i>
              </button>
            </div>
          </div>
          <!-- /.card-header -->
          <div class="card-body p-0">
            <ul class="users-list clearfix">
              {% for user in users_registered|slice:":10" %}
                <li>
                  {% if user.image_profile %}
                    <img class="img-circle img-circle-90" src="{{ user.image_profile.url }}" alt="User Image">
                  {% else %}
                    <img class="img-circle img-circle-90" src="{% static 'adminlte-3.1.0/dist/img/unknow_user.png' %}" alt="User Image">
                  {% endif %}

                  {% if perms.user.view_user %}
                    <a class="users-list-name" href="{% url 'user-detail' user.pk %}">{{ user.username }}</a>
                  {% else %}
                    <a class="users-list-name" href="javascript:;">{{ user.username }}</a>
                  {% endif %}
                  <span class="users-list-date">{{ user.date_joined|date:"d M"}}</span>
                </li>
              {% endfor %}
            </ul>
            <!-- /.users-list -->
          </div>
          <!-- /.card-body -->
          <div class="card-footer text-center">
            {% if perms.user.view_user %}
              <a href="{% url 'proforest-dashboard1' %}">Ver todos </a>
            {% else %}
              <a href="javascript:;" class="disabled">Ver todos </a>
            {% endif %}
          </div>
          <!-- /.card-footer -->
        </div>
        <!--/.card -->

      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </div>
  <!--/. container-fluid -->
</section>
<!-- /.content -->
{% endblock %}

{% block extra_js %}
<script src="{% static 'adminlte-3.1.0/plugins/chart.js/chart.min.js' %}"></script>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

<script type="text/javascript">

  window.addEventListener('DOMContentLoaded', (event) => {

    google.charts.load('current', {packages: ['corechart', 'line']});
google.charts.setOnLoadCallback(drawBasic);

function drawBasic() {

      var data = new google.visualization.DataTable();
      data.addColumn('string', 'Date');
      data.addColumn('number', 'fiat');

      data.addRows([
        {% for crypto_history in crypto_fiat_history %}
          ["{{crypto_history.date|date:"H:i"}}", {{crypto_history.fiat|stringformat:".2f"}}],
        {% endfor %}
      ]);

      var options = {
        vAxis: {
          title: 'USD'
        }
      };

      var chart = new google.visualization.LineChart(document.getElementById('crypto-fiat-chart'));

      chart.draw(data, options);
    }

  });

  /* div id = crypto-fiat-chart */
</script>
{% endblock %}